spring:
  application:
    name: jpa
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    open-in-view: false
    show-sql: true        # The simplest way to dump the queries to standard out
    properties:
      hibernate:
        format_sql: true  # pretty-print the SQL
  h2:
    console:
      enabled: true

logging:
  level:
    root: debug
    org.hibernate.orm.jdbc.bind: TRACE  # log a query with binding parameters