spring:
  application:
    name: jpa
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    open-in-view: false
  h2:
    console:
      enabled: true

logging:
  level:
    root: debug
